CREATE DATABASE PROYECTO_GDI
GO

USE PROYECTO_GDI
GO

CREATE TABLE DBO.CIUDAD
( 
	CIU_ID               INT  NOT NULL ,
	CIU_NOMBRE           VARCHAR(15)  NULL ,
	CONSTRAINT XPKCIUDAD PRIMARY KEY (CIU_ID ASC)
)
GO



CREATE TABLE DBO.GERENTE
( 
	GRT_ID               	INT  NOT NULL ,
	GRT_NOMBRE           	VARCHAR(30)  NULL ,
	GRT_APEPATERNO         	VARCHAR(15)  NULL ,
GRT_APEMATERNO         	VARCHAR(15)  NULL ,
	GRT_NROIDENTIFICACION   	CHAR(8)  NULL ,
	GRT_SEXO             	VARCHAR(10)  NULL ,
	GRT_EMAIL            	VARCHAR(50)  NULL ,
	GRT_TELEFONO         	VARCHAR(15)  NULL ,
	GRT_FECHANAC         	DATE  NULL ,
	CIU_ID               	INT  NULL ,
	CONSTRAINT XPKGERENTE PRIMARY KEY (GRT_ID ASC),
	CONSTRAINT R_12 FOREIGN KEY (CIU_ID) REFERENCES DBO.CIUDAD(CIU_ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
)
GO



CREATE TABLE DBO.CLIENTE
( 
	CLI_ID               	INT  NOT NULL ,
	CLI_NOMBRE           	VARCHAR(30)  NOT NULL ,
	GRT_APEPATERNO         	VARCHAR(15)  NULL ,
GRT_APEMATERNO         	VARCHAR(15)  NULL ,
	GRT_NROIDENTIFICACION   	CHAR(8)  NULL ,
	CLI_SEXO             	VARCHAR(10)  NOT NULL ,
	CLI_FECHANAC         	DATE  NOT NULL ,
	CLI_EMAIL            	VARCHAR(50)  NOT NULL ,
	CLI_TELEFONO         	VARCHAR(15)  NOT NULL ,
	CLI_RUC              	CHAR(11)  NOT NULL ,
	CIU_ID               	INT  NULL ,
	CONSTRAINT XPKCLIENTE PRIMARY KEY (CLI_ID ASC),
	CONSTRAINT R_16 FOREIGN KEY (CIU_ID) REFERENCES DBO.CIUDAD(CIU_ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
)
GO



CREATE TABLE DBO.TURNO
( 
	TURNO_ID             INT  NOT NULL ,
	TURNO_NOMBRE         VARCHAR(10)  NULL ,
	TURNO_HORARIO        VARCHAR(30)  NULL ,
	CONSTRAINT XPKTURNO PRIMARY KEY (TURNO_ID ASC)
)
GO



CREATE TABLE DBO.ASESORES
( 
	ASR_ID               	INT  NOT NULL ,
	ASR_NOMBRE           	VARCHAR(30)  NULL ,
	GRT_APEPATERNO         	VARCHAR(15)  NULL ,
GRT_APEMATERNO         	VARCHAR(15)  NULL ,
	GRT_NROIDENTIFICACION   	CHAR(8)  NULL ,
	ASR_FECHANAC         	DATE  NULL ,
	ASR_SEXO             	VARCHAR(10)  NULL ,
	ASR_EMAIL            	VARCHAR(50)  NULL ,
	ASR_TELEFONO         	VARCHAR(15)  NULL ,
	ASR_SUELDO           	NUMERIC  NULL ,
	CIU_ID               	INT  NULL ,
	TURNO_ID             	INT  NULL ,
	CONSTRAINT XPKASESORES PRIMARY KEY (ASR_ID ASC),
	CONSTRAINT R_13 FOREIGN KEY (CIU_ID) REFERENCES DBO.CIUDAD(CIU_ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION,
CONSTRAINT R_18 FOREIGN KEY (TURNO_ID) REFERENCES DBO.TURNO(TURNO_ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
)
GO



CREATE TABLE DBO.PLANES
( 
	PLN_ID               INT  NOT NULL ,
	PLN_NOMBRE           VARCHAR(10)  NOT NULL ,
	PLN_COSTO            NUMERIC  NOT NULL ,
	PLN_TRABAJADORES     INT  NOT NULL ,
	CONSTRAINT XPKPLAN PRIMARY KEY (PLN_ID ASC)
)
GO



CREATE TABLE DBO.PEDIDO
( 
	PDD_ID               INT  NOT NULL ,
	CLI_ID               INT  NULL ,
	ASR_ID               INT  NULL ,
	PLN_ID               INT  NULL ,
	PDD_MESES            INT  NULL ,
	PDD_TOTAL            NUMERIC  NULL ,
	PDD_FECHA            DATE  NULL ,
	CONSTRAINT XPKPEDIDO PRIMARY KEY (PDD_ID ASC),
	CONSTRAINT R_22 FOREIGN KEY (CLI_ID) REFERENCES DBO.CLIENTE(CLI_ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION,
CONSTRAINT R_23 FOREIGN KEY (ASR_ID) REFERENCES DBO.ASESORES(ASR_ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION,
CONSTRAINT R_24 FOREIGN KEY (PLN_ID) REFERENCES DBO.PLANES(PLN_ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
)
GO



CREATE TABLE DBO.ASESORIAS
( 
	ASES_ID              INT  NOT NULL ,
	CLI_ID               INT  NULL ,
	ASR_ID               INT  NULL ,
	ASES_FECHA           DATE  NOT NULL ,
	ASES_OBSERV          VARCHAR(200)  NOT NULL ,
	ESTADO               VARCHAR(10)  NOT NULL ,
	CONSTRAINT XPKASESORIAS PRIMARY KEY (ASES_ID ASC),
	CONSTRAINT R_19 FOREIGN KEY (ASR_ID) REFERENCES DBO.ASESORES(ASR_ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION,
CONSTRAINT R_20 FOREIGN KEY (CLI_ID) REFERENCES DBO.CLIENTE(CLI_ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
)
GO